User/ideen/tel 30
UCSolarCarTeam/Helios-Telemetry pull request #10
Opened 2023-02-01 03:23 UTC by ideen1

2023-02-01 03:28 UTC, Dillonsd requested changes
Small styling.

2023-02-01 03:28 UTC, Dillonsd commented on web-app/src/PacketContext.tsx
> +}
Newline

2023-02-01 03:28 UTC, Dillonsd commented on web-app/src/objects/telemetry-data.interface.ts
> +
New line

2023-02-04 17:59 UTC, JensVarughese reviewed
It would be nice to have a configExample.ts, like in the server so people will know the format of Config.ts

2023-02-04 22:00 UTC, jjason-nn approved these changes
Looks good

2023-02-04 22:07 UTC, Dillonsd approved these changes

2023-02-04 22:10 UTC, merged