Map.tsx
UCSolarCarTeam/Helios-Telemetry pull request #118
Opened 2024-07-30 02:49 UTC by David-Rodriguez-Barrios

2024-07-30 03:11 UTC, justin-phxm requested changes

2024-07-30 03:11 UTC, justin-phxm commented on packages/client/src/components/molecules/MapMolecules/Map.tsx
> +        coordinates !== undefined && i < coordinates.length;
see if you can optimize htis

2024-08-03 19:32 UTC, justin-phxm approved these changes
LGTM

2024-08-03 19:36 UTC, JenniferJa approved these changes

2024-08-03 19:36 UTC, merged