Tel 169 make the important pis data favourable
UCSolarCarTeam/Helios-Telemetry pull request #145
Opened 2024-10-12 16:57 UTC by alexwhelan12

2024-10-12 21:54 UTC, burtonjong requested changes

2024-10-12 21:54 UTC, burtonjong commented on packages/client/src/components/containers/BottomInformationContainer.tsx
> +// };
Delete

2024-10-12 21:54 UTC, burtonjong commented on packages/client/src/components/containers/BottomInformationContainer.tsx
>            <div className="text-helios">{fakeData["Bus Voltage"]}</div>
delete commetns

2024-10-12 21:59 UTC, kr1s-r approved these changes
looks good

2024-10-15 23:54 UTC, burtonjong approved these changes

2024-10-16 00:44 UTC, burtonjong submitted a review, later dismissed
lgtm for now

2024-10-18 23:52 UTC, justin-phxm requested changes
Let's chat about this on Saturday

2024-10-19 17:39 UTC, alexwhelan12 commented on packages/client/package.json
> +    "lodash": "^4.17.21",
Is Lodash not the most efficient way to compare 2 objects?

2024-10-19 19:10 UTC, justin-phxm commented on packages/client/package.json
> +    "lodash": "^4.17.21",
No. We don't want to add a new library just for one function.

2024-10-20 00:18 UTC, justin-phxm commented
Can you remove the favorite by clicking on the name in the bottom bar

2024-10-20 01:43 UTC, justin-phxm commented on packages/client/src/components/transformers/PISTransformer.tsx
> +      }
```suggestion
      }
      parsedFavourites.push(field.name);
      setCurrentAppState((prev) => ({
        ...prev,
        favourites: parsedFavourites,
      }));
      localStorage.setItem("favourites", JSON.stringify(parsedFavourites));
```

2024-10-20 01:43 UTC, justin-phxm commented on packages/client/src/components/containers/BottomInformationContainer.tsx
> +
```suggestion

```

2024-11-02 20:27 UTC, brian-ngyn commented on packages/client/src/components/transformers/PISTransformer.tsx
> +    <div>
dont need an extra div here just use <>

2024-11-02 20:27 UTC, brian-ngyn commented on packages/client/src/components/transformers/PISTransformer.tsx
> +  const handleAddToFavourites = () => {
usecallback

2024-11-02 22:32 UTC, justin-phxm requested changes
I think it's almost ready for prod, just a few more changes. Try to write as little code as possible. I noticed there are lots of redundant lines and conditionals that make it much harder to review. Less code is better code.

Also, ask Kris to walk you through on git commit --amend. You have too many commits!!

2024-11-02 22:32 UTC, justin-phxm commented on packages/client/src/components/transformers/PISTransformer.tsx
> +        ? (min === undefined || (typeof value === "number" && value >= min)) &&
you are using both valueType and typeof value here. Just use one or the other

2024-11-02 22:32 UTC, justin-phxm commented on packages/client/src/contexts/AppStateContext.tsx
> +import { PausePresentationRounded } from "@mui/icons-material";
What is this doing here?

2024-11-02 22:32 UTC, justin-phxm commented on packages/client/src/components/transformers/PISTransformer.tsx
> +  // const [favorites,setFavorites]= useState([]); MAKE THIS A CONTEXT
I think we should delete commented out code.

2024-11-02 22:32 UTC, justin-phxm commented on packages/client/src/components/transformers/PISTransformer.tsx
> +      {isHovered && field.isFault === undefined ? (
Can we move this conditional one element down? We are duplicating some code.

2024-11-02 22:32 UTC, justin-phxm commented on packages/client/src/contexts/AppStateContext.tsx
> +        appUnits: parsedSettings.appUnits,
Is there a reason why we are changing the appUnits, connectionType, and darkMode?

2024-11-02 22:32 UTC, justin-phxm commented on packages/client/src/components/containers/BottomInformationContainer.tsx
> +        newFavourites.push(
Can we just have it empty instead of having this default?

2024-11-02 22:32 UTC, justin-phxm commented on packages/client/src/components/containers/BottomInformationContainer.tsx
> +interface HandleRemoveFavourite {
Can we have this as an inline type instead

2024-11-02 22:32 UTC, justin-phxm commented on packages/client/src/components/containers/BottomInformationContainer.tsx
> +  const favourites = currentAppState?.favourites ?? [];
Are these checks really necessary?

2024-11-02 22:32 UTC, justin-phxm commented on packages/client/src/components/containers/BottomInformationContainer.tsx
> +      return undefined; // Return undefined if no matching name is found
I don't think we need this

2024-11-02 22:32 UTC, justin-phxm commented on packages/client/src/components/containers/BottomInformationContainer.tsx
> +          return undefined; // Return undefined if no matching name is found
I don't think we need this

2024-11-02 22:32 UTC, justin-phxm commented on packages/client/src/components/transformers/PISTransformer.tsx
> +  const [isHovered, setIsHovered] = useState(false);
Do you even need this? Just use css hover: state

2024-11-06 01:37 UTC, alexwhelan12 commented on packages/client/src/contexts/AppStateContext.tsx
> +        appUnits: parsedSettings.appUnits,
appUnits, connectionType and darkMode are not ever getting changed, it just sets the value for favourites differently depending if there were any favourites saved locally or not. The appUnits, connectionType and darkMode are set to the same value in either case.

2024-11-06 01:57 UTC, brian-ngyn approved these changes

2024-11-06 01:58 UTC, burtonjong approved these changes
YYYAYYYYYY

2024-11-06 01:59 UTC, merged