TEL-205-create-tab-for-analysis-with-graphs-and-stats-subtab
UCSolarCarTeam/Helios-Telemetry pull request #156
Opened 2024-11-02 17:10 UTC by kr1s-r

2024-11-02 19:20 UTC, burtonjong requested changes

2024-11-02 19:20 UTC, burtonjong commented on packages/client/src/components/tabs/AnalysisTab.tsx
> +];
can we move these to TabRoutes.tsx instead and import them from there

2024-11-02 19:20 UTC, burtonjong commented on packages/client/src/components/tabs/AnalysisTab.tsx
> +};
Move this to TabRoutes.tsx again

2024-11-02 20:08 UTC, burtonjong submitted a review, later dismissed
LGTM

2024-11-02 20:37 UTC, brian-ngyn commented on packages/client/src/components/tabs/AnalysisTab.tsx
> +  children: React.ReactNode;
can you use PropsWithChildren

2024-11-02 21:32 UTC, burtonjong approved these changes
LGTM

2024-11-06 00:48 UTC, alexwhelan12 approved these changes
LGTM!

2024-11-06 00:49 UTC, merged