Tel 210 mqtt username
UCSolarCarTeam/Helios-Telemetry pull request #169
Opened 2024-11-23 21:20 UTC by David-Rodriguez-Barrios

### Summary

- MQTT username and password will now be stored in the AWS Secrets Manager
- Gives the ECS Task Definition access to the secrets to connect with the respective credentials
- Updates our server to use the new credentials in the MQTT Client

### To Do

- Give VisComm the updated credentials next time we do integration tests.

2024-12-08 04:45 UTC, ideen1 requested changes
Few comments

2024-12-08 04:45 UTC, ideen1 commented on Dockerfile
> +# ENV MQTT_PASSWORD=${MQTT_PASSWORD}
Not needed

2024-12-08 04:45 UTC, ideen1 commented on Dockerfile
> +# ENV MQTT_USERNAME=${MQTT_USERNAME}
Not needed

2024-12-08 04:45 UTC, ideen1 commented on packages/amplify/amplify/backend.ts
> +const MQTT_PASSWORD_ENV = process.env.MQTT_PASSWORD_ENV;
Want to confirm, you are setting these in the Amplify Deploy Job? I would recommend against this and instead setting them directly in secrets manager. We don't want to run a full deployment just to update the secrets imo.

2024-12-08 04:45 UTC, ideen1 commented on packages/amplify/amplify/backend.ts
> +      "username"
Looks good!

2024-12-11 21:37 UTC, David-Rodriguez-Barrios commented on packages/amplify/amplify/backend.ts
> +const MQTT_PASSWORD_ENV = process.env.MQTT_PASSWORD_ENV;
I was setting these as env variables in the Amplify deployment, but adding them to the secrets manager directly works too. (better practice overall too)

2025-01-12 03:10 UTC, justin-phxm commented
fixed in https://github.com/UCSolarCarTeam/Helios-Telemetry/pull/178

2025-01-12 03:11 UTC, closed without merging