made filters clickable
UCSolarCarTeam/Helios-Telemetry pull request #170
Opened 2024-11-23 21:47 UTC by kr1s-r

2024-11-30 18:27 UTC, justin-phxm requested changes
rebase off main

2024-11-30 18:27 UTC, justin-phxm commented on packages/client/src/components/tabs/AnalysisTab.tsx
> +                  className="h-4 w-4 accent-[#B94A6C]"
```suggestion
                  className="size-4 accent-custom-color"
```

Can we also add this custom color to the tailwind config file?

2024-12-01 00:22 UTC, justin-phxm approved these changes

2024-12-01 00:24 UTC, justin-phxm requested changes
![image](https://github.com/user-attachments/assets/58144a1c-600d-49f0-80f8-c2f6cf51a083)

Can you center the checkbox and the text. Also, It should be a pointer when you hover over the checkbox...

Instead of using space-x-2, use gap-2 on the parent.

2024-12-07 22:34 UTC, alexwhelan12 approved these changes
LGTM!

2024-12-07 22:35 UTC, merged