car parts blink red, or orange
UCSolarCarTeam/Helios-Telemetry pull request #57
Opened 2024-01-27 20:57 UTC by JenniferJa

2024-01-30 04:40 UTC, ideen1 commented
Remember to  rebase this change on top of main  before submitting 💯

2024-02-03 22:20 UTC, CalebBourb commented on app/src/renderer/code/components/molecules/HeroMolecules/CarGraphicComponent.tsx
It's best practice to add a line of whitespace at the end of the file

2024-02-03 22:24 UTC, alexwhelan12 approved these changes
Looks good to me!

2024-02-03 22:25 UTC, CalebBourb commented on app/src/renderer/code/components/molecules/HeroMolecules/CarMolecules/CarModelComponent.tsx
same as before, add a line to the end of the file.

2024-02-03 22:26 UTC, CalebBourb commented on app/src/renderer/code/components/molecules/HeroMolecules/CarGraphicComponent.tsx
> -import React, { useState } from "react";
It's best practice to add a line of whitespace at the end of the file

2024-02-03 22:27 UTC, CalebBourb commented on app/src/renderer/code/components/molecules/HeroMolecules/CarMolecules/CarModelComponent.tsx
> +import { IndicationLocations, IndicationStates } from "../CarGraphicComponent";
same as before, add a line to the end of the file.

2024-02-03 22:28 UTC, CalebBourb requested changes
Need blank lines at the end of your files for best practices

2024-02-06 03:14 UTC, IshaHaider reviewed
reviewed. Looks good!

2024-02-13 02:26 UTC, IshaHaider approved these changes
LGTM

2024-02-13 02:36 UTC, brian-ngyn approved these changes

2024-02-13 02:41 UTC, merged