Pis layout work
UCSolarCarTeam/Helios-Telemetry pull request #62
Opened 2024-02-03 18:26 UTC by justin-phxm

2024-02-03 22:14 UTC, ideen1 requested changes
Please make the styling look identical to what is currently on main

2024-02-03 22:14 UTC, ideen1 commented on app/src/renderer/code/App.tsx
> +      <div className="size-screen overflow-x-hidden bg-light p-4 text-light dark:bg-dark dark:text-dark">
Please remove general App staying changes. These will eb handled in a different ticket

2024-02-03 22:14 UTC, ideen1 commented on app/src/renderer/code/App.tsx
> +            <div className="size-96 grow">
Please remove general App staying changes. These will eb handled in a different ticket

2024-02-03 22:14 UTC, ideen1 commented on app/src/renderer/code/components/atoms/FaultCard.tsx
> +          className={`flex size-full items-center justify-start border p-2${
Please remove general App staying changes. These will eb handled in a different ticket

2024-02-03 22:14 UTC, ideen1 commented on app/src/renderer/code/components/containers/HeroContainer.tsx
> +      <div className="grid size-full grid-cols-1 gap-4 md:grid-cols-6">
Please remove general App styling changes. These will eb handled in a different ticket

2024-02-03 22:14 UTC, ideen1 commented on app/src/renderer/code/components/containers/MapContainer.tsx
> +    <div className="size-full">
Please remove general App styling changes. These will be handled in a different ticket

2024-02-03 22:14 UTC, ideen1 commented on app/src/renderer/code/components/molecules/HeroMolecules/CarGraphicComponent.tsx
> +/* eslint-disable react/no-unknown-property */
@justin-phxm @brian-ngyn What are these ignores for? We should try to remove them if possible

2024-02-13 02:35 UTC, IshaHaider submitted a review, later dismissed

2024-02-13 03:39 UTC, ideen1 approved these changes

2024-02-13 03:42 UTC, brian-ngyn approved these changes

2024-02-13 03:43 UTC, merged