change to @ import
UCSolarCarTeam/Helios-Telemetry pull request #63
Opened 2024-02-03 20:32 UTC by brian-ngyn

2024-02-03 22:10 UTC, ideen1 requested changes
Please ensure the styling of the site is identical to what is currently on main.

2024-02-03 22:10 UTC, ideen1 commented on app/src/renderer/code/App.tsx
> +      <div className="size-screen overflow-x-hidden bg-light p-4 text-light dark:bg-dark dark:text-dark">
Please remove general App staying changes. These will be handled in a different ticket

2024-02-03 22:10 UTC, ideen1 commented on app/src/renderer/code/App.tsx
> +            <div className="size-96 grow">
Please remove general App staying changes. These will eb handled in a different ticket

2024-02-03 22:10 UTC, ideen1 commented on app/src/renderer/code/components/atoms/FaultCard.tsx
> +          className={`flex size-full items-center justify-start border p-2${
Please remove general App staying changes. These will eb handled in a different ticket

2024-02-04 08:28 UTC, ideen1 requested changes
Looks good. Thanks for making the styling changes. As per @CalebBourb, please add the end of file new lines to our TS config. As discussed today, this may already be implemented, so instead can you add a husky hook to run prettier --write .? Let me know if you need any support with this. Once this is in, we can all rebase off of this awesome work and use all of the styling enforcements :)

2024-02-04 08:30 UTC, ideen1 commented
@UCSolarCarTeam/telemetry Please review this PR ASAP so we can get all our prettier/ ts rules in :) 

Feel free to point out anything you notice in terms of code styling, logic or questions you have about the code!!

2024-02-04 21:36 UTC, brian-ngyn commented
@UCSolarCarTeam/telemetry cherry pick 83e0f3b999c7e3aa4fc2c6891214c7c1202c637d into your current branches. You should run the following command from the Helios-Telemetry folder

```
git cherry-pick 83e0f3b999c7e3aa4fc2c6891214c7c1202c637d
```

Make sure to update your dependencies by running `npm install`
Also make sure you have Prettier and ESLint extensions installed

2024-02-04 23:02 UTC, ideen1 approved these changes
All looks good to me

2024-02-06 00:56 UTC, justin-phxm approved these changes
ok

2024-02-06 00:56 UTC, CalebBourb approved these changes
WOW i am amazed by the quality of this code! I wishto model my life after your work, it truly is an inspiration. 5/5

2024-02-06 00:56 UTC, merged