Pis structure mppt maarya jennifer
UCSolarCarTeam/Helios-Telemetry pull request #71
Opened 2024-02-10 20:53 UTC by maaryaahmed

finishing up the mppt PIS tab

2024-02-10 22:42 UTC, alexwhelan12 reviewed
Looks good to me.

2024-02-10 22:42 UTC, brian-ngyn approved these changes
LGTM

2024-02-13 02:15 UTC, IshaHaider requested changes

2024-02-13 02:15 UTC, IshaHaider commented on app/src/renderer/code/components/tabs/MpptTab.tsx
> +// };
remove all commented out code for clean up

2024-02-13 02:34 UTC, JenniferJa approved these changes

2024-02-25 01:51 UTC, merged