Tel 104 make hero component use packet context data
UCSolarCarTeam/Helios-Telemetry pull request #81
Opened 2024-03-16 17:39 UTC by alexwhelan12

2024-03-17 01:41 UTC, ideen1 requested changes
Looks great overall, just some code cleanup changes.

2024-03-17 01:41 UTC, ideen1 commented on client/src/components/atoms/SpeedAtom.tsx
>    const {} = useAppState;
This code is not needed, we can remove it.

2024-03-17 01:41 UTC, ideen1 commented on client/src/components/atoms/ThrottleIcon.tsx
>    const [throttleStyleString, setThrottleStyleString] = useState<string>("");
This code is not needed, we can remove it.

2024-03-17 01:41 UTC, ideen1 commented on client/src/components/atoms/ThrottleIcon.tsx
> +  // }, [regenPos, gasPos]);
This code is not needed, we can remove it.

2024-03-17 01:41 UTC, ideen1 commented on client/src/components/molecules/HeroMolecules/BatteryThrottleComponent.tsx
> +import type ITelemetryData from "@/objects/telemetry-data.interface";
This code is not needed, we can remove it.

2024-03-17 01:41 UTC, ideen1 commented on client/src/components/molecules/HeroMolecules/CarGraphicComponent.tsx
> +import type ITelemetryData from "@/objects/telemetry-data.interface";
This code is not needed, we can remove it.

2024-03-17 01:41 UTC, ideen1 commented on client/next.config.mjs
> +  webpack(config) {
Please undo changes in this file, theya re no longer needed.

2024-03-17 01:41 UTC, ideen1 commented on package.json
> +    "@svgr/webpack": "^8.1.0",
We can uninstall this library now that we no longer need it.

2024-03-17 01:41 UTC, ideen1 commented on .vscode/settings.json
> +  "[typescriptreact]": {
Remove this change

2024-03-23 21:44 UTC, ideen1 submitted a review, later dismissed

2024-03-23 21:57 UTC, JenniferJa approved these changes

2024-03-23 21:58 UTC, JenniferJa submitted a review, later dismissed

2024-03-23 22:06 UTC, JenniferJa approved these changes

2024-03-23 22:07 UTC, ideen1 approved these changes

2024-03-23 22:07 UTC, merged