settings modal, local storage and darkmode toggling implemented
UCSolarCarTeam/Helios-Telemetry pull request #84
Opened 2024-03-23 19:24 UTC by JenniferJa

2024-03-26 02:40 UTC, ideen1 requested changes

2024-03-26 02:40 UTC, ideen1 commented on client/src/contexts/AppStateContext.tsx
> +  "Network",
Add a value to the Enums like: `"Network" = NETWORK`

2024-03-26 02:40 UTC, ideen1 commented on client/src/contexts/AppStateContext.tsx
> +    connectionTypes: connectionTypes["Network"],
It's more common to access enums like this: `ConnectionTypes.NETWORK`

2024-03-26 02:40 UTC, ideen1 commented on client/src/contexts/AppStateContext.tsx
> +export enum connectionTypes {
Our convention is to use CapitalCase for Enum and Type Names

2024-03-26 02:40 UTC, ideen1 commented on client/src/contexts/AppStateContext.tsx
> +      JSON.stringify({
You cause just directly pass in `currentAppState` here.

2024-03-26 02:40 UTC, ideen1 commented on client/src/contexts/AppStateContext.tsx
> +      setCurrentAppState({
You can also just directly ready this from local storage without recreating the struct.

2024-04-06 20:18 UTC, brian-ngyn requested changes

2024-04-06 22:08 UTC, ideen1 approved these changes

2024-04-06 22:10 UTC, brian-ngyn approved these changes

2024-04-06 22:10 UTC, merged