Tel 107 add unit conversion to pis transformer
UCSolarCarTeam/Helios-Telemetry pull request #86
Opened 2024-04-06 20:51 UTC by ideen1

2024-04-06 20:57 UTC, brian-ngyn requested changes

2024-04-06 20:57 UTC, brian-ngyn commented on client/src/components/transformers/PISTransformer.tsx
> +  const appState = useAppState();
you should destructure `appState` so you don't have to do `appState.currentAppState` everytime

2024-04-06 20:58 UTC, brian-ngyn requested changes

2024-04-06 20:58 UTC, brian-ngyn commented on client/src/components/transformers/PISTransformer.tsx
> +  if (unit === UnitType.TEMP) {
can we use a case switch statement?

```
switch (unit) {
  case UnitType.TEMP:
    // your code here
    break;
  
  case UnitType.SPEED:
    // your code here
    break;
  
  case UnitType.DISTANCE:
    // your code here
    break;

  default:
    unitReturn = "";
    valueReturn = value;
}
```

2024-04-09 02:30 UTC, ideen1 commented on client/src/contexts/AppStateContext.tsx
> +export default APPUNITS;
Remove this

2024-05-07 05:49 UTC, ideen1 commented
Looks super good. Just one last thing: Can you round the miles per hour to 0 decimal places? Right now it shows 20 decimal places.

2024-05-12 04:38 UTC, justin-phxm approved these changes
LGTM

2024-05-22 00:24 UTC, brian-ngyn approved these changes

2024-05-22 00:24 UTC, merged