Loading screen
UCSolarCarTeam/Helios-Telemetry pull request #89
Opened 2024-05-11 21:41 UTC by JenniferJa

2024-05-12 04:20 UTC, justin-phxm submitted a review, later dismissed
LGTM

2024-05-21 05:29 UTC, ideen1 commented
I'm investigating an issue with loading background not appearing on Safari.

2024-05-21 23:45 UTC, brian-ngyn commented on client/src/contexts/AppStateContext.tsx
> +    }
you want to clear the timeout when this component unmounts

2024-06-02 16:02 UTC, ideen1 commented
Still need DOM callback and Socket IO callback

2024-06-04 00:54 UTC, alexwhelan12 submitted a review, later dismissed
Looks good to me!

2024-06-04 02:08 UTC, burtonjong commented on client/src/components/global/Loading.tsx
> +          <Image
The sun should be behind the car

2024-06-04 02:20 UTC, justin-phxm commented on client/src/components/global/LoadingWrapper.tsx
> +      setTimeout(() => {
need to clear this timeout

2024-06-04 02:21 UTC, justin-phxm requested changes

2024-06-04 02:21 UTC, justin-phxm commented on client/src/components/global/LoadingWrapper.tsx
> +    setTimeout(() => {
clear timeout

2024-06-08 22:17 UTC, justin-phxm submitted a review, later dismissed
LGTM

2024-06-08 23:03 UTC, alexwhelan12 approved these changes
LGTM!

2024-06-09 04:06 UTC, burtonjong approved these changes
wheres the weather effects??? JK LGTM

2024-06-09 04:21 UTC, brian-ngyn requested changes

2024-06-09 04:21 UTC, brian-ngyn commented on client/src/components/global/LoadingWrapper.tsx
> +  }, [currentLoadingState]);
we shouldn't conditionally create timeouts, i don't doubt if they are actually being cleared or not

```
useEffect(() => {
    let driveInTimeout: NodeJS.Timeout;
    let pendingTimeout: NodeJS.Timeout;
    let readyTimeout: NodeJS.Timeout;
    let confirmTimeout: NodeJS.Timeout;

    // Start with DRIVE_IN stage
    driveInTimeout = setTimeout(() => {
      setCurrentLoadingStage(LOADINGSTAGES.PENDING);
    }, 1000);

    // Switch to READY stage if loading is complete
    if (!currentAppState.loading) {
      pendingTimeout = setTimeout(() => {
        setCurrentLoadingStage(LOADINGSTAGES.READY);
      }, 4000);
    }

    // Confirm visual loading fulfillment if in READY stage
    if (currentLoadingState === LOADINGSTAGES.READY) {
      confirmTimeout = setTimeout(() => {
        confirmVisualLoadingFulfilledAndReady();
      }, 800);
    }

    // Cleanup all timeouts on component unmount or state change
    return () => {
      clearTimeout(driveInTimeout);
      clearTimeout(pendingTimeout);
      clearTimeout(readyTimeout);
      clearTimeout(confirmTimeout);
    };
  }, [currentAppState.loading, currentLoadingState, confirmVisualLoadingFulfilledAndReady]);
```

2024-06-09 04:21 UTC, brian-ngyn commented on client/src/components/global/Loading.tsx
> +          }
can we do it like this?

```
const LoadingMessage = {
  [LOADINGSTAGES.DRIVE_IN]: "Connecting to Helios...",
  [LOADINGSTAGES.PENDING]: "Connecting to Helios...",
  [LOADINGSTAGES.READY]: "Connected to Helios!",
};
```

and then we render the following out inside the h2
```
{LoadingMessage[currentLoadingState]}
```

2024-06-09 04:21 UTC, brian-ngyn commented on client/src/components/global/Loading.tsx
> +            )}
this looks pretty messy, we can add this:

```
const carAnimationClass = useMemo(() => {
    switch (currentLoadingState) {
      case LOADINGSTAGES.PENDING:
        return "animate-bump";
      case LOADINGSTAGES.READY:
        return "animate-driveOffScreen";
      case LOADINGSTAGES.DRIVE_IN:
        return "animate-driveInScreen";
      default:
        return "";
    }
  }, [currentLoadingState]);
```

and then change the `className={twMerge("z-40", carAnimationClass)}`

2024-06-09 04:41 UTC, brian-ngyn commented
I'm wondering if we can create a loading context and a HOC like this:

```
const loadingContext = createContext<>({});

export const LoadingProvider = ({ children }) => {
  const [loading, setLoading] = useState(true);
  const [loadingCount, setLoadingCount] = useState(0);

  const startLoading = () => setLoadingCount((count) => count + 1);
  const finishLoading = () => setLoadingCount((count) => Math.max(count - 1, 0));

  useEffect(() => {
    setLoading(loadingCount > 0);
  }, [loadingCount]);

  return (
    <LoadingContext.Provider value={{ loading, startLoading, finishLoading }}>
      {children}
    </LoadingContext.Provider>
  );
};

export const useLoading = () => {
  return useContext(loadingContext);
}
```

```
const withLoading = (WrappedComponent) => {
  return (props) => {
    const { startLoading, finishLoading } = useLoading();

    useEffect(() => {
      startLoading();
      return () => finishLoading();
    }, [startLoading, finishLoading]);

    return <WrappedComponent {...props} />;
  };
};
```

and then wrap our expensive components
```
const ExpensiveComponent = ({ data }) => {
  return <>it renders something expensive or does an expensive calculation</>;
};

export default withLoading(ExpensiveComponent);
```

that way we can decouple our loading state from the appstatecontext? thoughts @ideen1 @justin-phxm

2024-06-09 16:37 UTC, justin-phxm reviewed
I was thinking maybe we could simplify a lot of the logic with React Suspense and Lazy Loading. 

https://react.dev/reference/react/Suspense

https://react.dev/reference/react/lazy

2024-06-10 07:19 UTC, ideen1 commented
> I was thinking maybe we could simplify a lot of the logic with React Suspense and Lazy Loading.
> 
> https://react.dev/reference/react/Suspense
> 
> https://react.dev/reference/react/lazy

I agree but I think the issue with Suspense is that it may hide the loader before the animation is done. if we could tie in Suspense to notify us, then we can trigger our animation to finish and hide the loader

2024-06-10 07:22 UTC, ideen1 commented
> I'm wondering if we can create a loading context and a HOC like this:
> 
> ```
> const loadingContext = createContext<>({});
> 
> export const LoadingProvider = ({ children }) => {
>   const [loading, setLoading] = useState(true);
>   const [loadingCount, setLoadingCount] = useState(0);
> 
>   const startLoading = () => setLoadingCount((count) => count + 1);
>   const finishLoading = () => setLoadingCount((count) => Math.max(count - 1, 0));
> 
>   useEffect(() => {
>     setLoading(loadingCount > 0);
>   }, [loadingCount]);
> 
>   return (
>     <LoadingContext.Provider value={{ loading, startLoading, finishLoading }}>
>       {children}
>     </LoadingContext.Provider>
>   );
> };
> 
> export const useLoading = () => {
>   return useContext(loadingContext);
> }
> ```
> 
>  ```
> const withLoading = (WrappedComponent) => {
>   return (props) => {
>     const { startLoading, finishLoading } = useLoading();
> 
>     useEffect(() => {
>       startLoading();
>       return () => finishLoading();
>     }, [startLoading, finishLoading]);
> 
>     return <WrappedComponent {...props} />;
>   };
> };
> ```
> 
> and then wrap our expensive components
> 
> ```
> const ExpensiveComponent = ({ data }) => {
>   return <>it renders something expensive or does an expensive calculation</>;
> };
> 
> export default withLoading(ExpensiveComponent);
> ```
> 
> that way we can decouple our loading state from the appstatecontext? thoughts @ideen1 @justin-phxm

I like this a lot. Only thing is I don't think we should only wrap the car graphic:
1. We want the socket connection itself to be something that we wait on for loading(it's not even a visual component but rather something where we need to set that loading is complete upon socket.connected)
2. I think the entire PIS section, car graphic section could be expensive components for the purposes of the loading screen so we should wrap both of those.

2024-06-11 02:15 UTC, ideen1 commented
The loading HOC discussion will be completed in this ticket: https://uofcsolarcar.atlassian.net/browse/TEL-116

2024-06-11 02:22 UTC, ideen1 commented
LGTM

2024-06-11 02:22 UTC, ideen1 approved these changes
LGTM

2024-06-11 02:23 UTC, burtonjong approved these changes
hlmggtm,

2024-06-11 02:26 UTC, brian-ngyn requested changes

2024-06-11 02:26 UTC, merged